name: Compile
on:
  push:
jobs:
  react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile React
        uses: Pewaukee-Watershed/compiler-actions@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
